INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (unit_Of_Measure) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (unit_Of_Measure) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (unit_Of_Measure) VALUES ('Cup');
INSERT INTO unit_of_measure (unit_Of_Measure) VALUES ('Pinch');
INSERT INTO unit_of_measure (unit_Of_Measure) VALUES ('Ounce');
INSERT INTO unit_of_measure (unit_Of_Measure) VALUES ('Pint');
INSERT INTO unit_of_measure (unit_Of_Measure) VALUES ('Each');
INSERT INTO unit_of_measure (unit_Of_Measure) VALUES ('Dash');